package com.demo.Repository.AttpayEmpmstRepository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.demo.Model.AttpayEmpmst.AttpayEmpmst;

@Repository
public interface AttpayEmpmstRepository extends JpaRepository<AttpayEmpmst, Integer> {
    
	@Query(nativeQuery = true, value = "SELECT * FROM ATTPAY_EMPMST LIMIT 2300;")
	
//	@Query(nativeQuery = true, value = "SELECT EMP_NO, PAY_EMP_NO, APPROVED, APPROVED_BY, APPROVED_DATE, CANCELED, CHANGED, CHANGED_DATE, CREATED_BY, CREATED_DATE, DOC_DATE,"
//			+ "EMP_ADHAAR_NO, EMP_ADDLN_AMOUNT, EMP_BANK_ACCOUNT_NO, EMP_BANK_NAME, EMP_BASIC_RATE, EMP_BIRTH_DATE, EMP_BLOODGROUP, EMP_CATEGORY, EMP_CHQ_RETAINER_FEE, EMP_CITY, EMP_COMPANY,"
//			+ "EMP_CONFIRM_DATE, EMP_CORRES_ADDRESS, EMP_COUNTRY, EMP_DEPARTMENT, EMP_DESIGNATION, EMP_DISTRICT, EMP_DIVISION, EMP_ELECTRICITY, EMP_EMAIL, EMP_ESI_NO, EMP_GRADE, EMP_HRA,"
//			+ "EMP_INCREMENT_DUE_DATE, EMP_INCREMENT_LAST_DUE_DATE, EMP_INCREMENT_NEXT_DUE_DATE, EMP_JOIN_DATE, EMP_JOIN_DATE_GRATUITY, EMP_LEFT_DATE, EMP_MAGAZINE, EMP_MAIN_CATEGORY,"
//			+ "EMP_MARITAL_STATUS, EMP_NAME, EMP_NOMINATION_GRATUITY, EMP_NOMINATION_PF, EMP_OLD_ESIC_DAYS, EMP_PAN_NO, EMP_PERM_ADDRESS, EMP_PERSONAL_PAY, EMP_PETROL_LTRS, EMP_PF_NO, EMP_PHONE,"
//			+ "EMP_PINCODE, EMP_QUALIFICATION, EMP_SEX, EMP_SHIFT_CATEGORY_COSEC, EMP_SHIFT_ID, EMP_SHIFT_ID_COSEC, EMP_STATE, EMP_SUPERANNUATION, EMP_UAN_NO, EMP_VEHICLE_NO, EMP_WASHING_ALLOWANCE,"
//			+ "EMP_WEEKOFF, EMP_WEEKOFF_DAY, FULL_PRESENT_IND, FULL_PRESENT_UPTO_DATE, HIERARCHY_ID, IP_CREATER, IP_MODIFIER, MODIFIED_BY, MODIFIED_DATE, PL_RULE, REJECTED, REJECTED_BY, REJECTED_DATE"
//			+ " FROM ATTPAY_EMPMST LIMIT 2300;")
	List<AttpayEmpmst> getAttpayEmpmstList();
	
}
